# action.yml
name: 'AI Code review'
description: 'Uses AI to provide assisted summarisation and feedback for Pull requests'
inputs:
  pr_number:
    description: 'The Pull Request number'
    required: true
  repository:
    description: 'The Github repository'
    required: true
  token:
    description: 'The Github token to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PR_NUMBER: ${{ inputs.pr_number }}
    GITHUB_TOKEN: ${{ inputs.token }}
    GITHUB_REPOSITORY: ${{ inputs.repository }}
