# action.yml
name: 'AI Code review'
description: 'Uses AI to provide assisted summarisation and feedback for Pull requests'
inputs:
  pr_number:
    description: 'The Pull Request number'
    required: true
  repository:
    description: 'The Github repository'
    required: true
  token:
    description: 'The Github token to use'
    required: true
  openai_api_key:
    description: 'The OpenAPI API key'
    required: true
  reviewed_label:
    description: 'The label to add after reviewing'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PR_NUMBER: ${{ inputs.pr_number }}
    GITHUB_TOKEN: ${{ inputs.token }}
    GITHUB_REPOSITORY: ${{ inputs.repository }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    REVIEWED_LABEL: ${{ inputs.reviewed_label }}
