# action.yml
name: 'AI Code review'
description: 'Uses AI to provide assisted summarisation and feedback for Pull requests'
inputs:
  pr_number:
    description: 'The Pull Request number'
    required: true
  repository:
    description: 'The Github repository'
    required: true
  token:
    description: 'The Github token to use'
    required: true
  openai_api_key:
    description: 'The OpenAPI API key'
    required: true
  openai_model:
    description: 'The OpenAPI model to use'
    required: false
  openai_max_tokens:
    description: 'The max number of tokens to return in the code review response'
    required: false
  reviewed_label:
    description: 'The label to add after reviewing'
    required: false
  log_level:
    description: 'The log level. One of: error, warn, info (default), debug.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PR_NUMBER: ${{ inputs.pr_number }}
    GITHUB_TOKEN: ${{ inputs.token }}
    GITHUB_REPOSITORY: ${{ inputs.repository }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    OPENAI_MODEL: ${{ inputs.openai_model }}
    OPENAI_MAX_TOKENS: ${{ inputs.openai_max_tokens }}
    REVIEWED_LABEL: ${{ inputs.reviewed_label }}
    LOG_LEVEL: ${{ inputs.log_level }}
