name: 'Master build'

on:
  push:
    branches:
      - 'main'

run-name: 'Master build #${{github.run_number}}'

env:
  NODE_VERSION: '20'

jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      imageTag: ${{ steps.nextVersion.outputs.nextVersion }}

    steps:
      - 
        name: Checkout the branch
        uses: actions/checkout@v4
      - 
        name: Get tags
        run: git fetch --tags origin
      - 
        name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - 
        name: Install Node modules
        run: npm install
      - 
        name: Test
        run: npm test
      - 
        name: Check dist
        run: |
          npx ncc build src/main/js/index.js -o tmp --minify
          actual_hash=$(sha256sum dist/index.js | awk '{print $1}')
          expected_hash=$(sha256sum tmp/index.js | awk '{print $1}')

          echo "Expected hash: $expected_hash"
          echo "Actual hash:   $actual_hash"

          if [ "$expected_hash" != "$actual_hash" ]; then
            echo "❌ The dist/index.js file is out of sync with the source."
            echo "💡 Please run \`npm run package\` and commit the result."
            exit 1
          else
            echo "✅ dist/index.js is up to date."
          fi
      - 
        name: Determine next version number
        id: nextVersion
        uses: newsome-solutions-ltd/release-version-action@main
        with:
          versionScheme: '0.x'

  tag:

    runs-on: ubuntu-latest

    needs: [build]

    steps:
      -
        name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ needs.build.outputs.imageTag }}',
              sha: context.sha
            })
    
  release:

    runs-on: ubuntu-latest

    needs: [build,tag]

    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      - 
        name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 'v${{ needs.build.outputs.imageTag }}'
          name: 'v${{ needs.build.outputs.imageTag }}'
          draft: false
          prerelease: false
