name: 'Pull request build'

run-name: 'Pull request build [PR#${{ github.ref_name }}] #${{ github.run_number }}'

on:
  pull_request:
    branches:
      - 'main'
      - 'release/**'

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout the branch
        uses: actions/checkout@v3
      - 
        name: Setup Node
        uses: actions/setup-node@v4

        with:
          node-version: ${{ env.NODE_VERSION }}
      - 
        name: Install Node modules
        run: npm install
      - 
        name: Test
        run: npm test
    
