name: 'Pull request build'

run-name: 'Pull request build [PR#${{ github.ref_name }}] #${{ github.run_number }}'

on:
  pull_request:
    branches:
      - 'main'
      - 'release/**'

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout the branch
        uses: actions/checkout@v4
      - 
        name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - 
        name: Install Node modules
        run: npm install
      - 
        name: Test
        run: npm test
      - 
        name: Package
        if: github.event_name == 'pull_request'
        run: |
          npx ncc build src/main/js/index.js -o tmp --minify
          actual_hash=$(sha256sum dist/index.js | awk '{print $1}')
          expected_hash=$(sha256sum tmp/index.js | awk '{print $1}')

          echo "Expected hash: $expected_hash"
          echo "Actual hash:   $actual_hash"

          if [ "$expected_hash" != "$actual_hash" ]; then
            echo "⚠️ The dist/index.js file is out of sync with the source, compiling..."
            npm run package
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add dist/index.js
            git commit -m "Auto-build dist/index.js"
            echo "✅ dist/index.js is now up to date, pusing changes to branch ${{ github.head_ref }}..."
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "✅ dist/index.js is up to date, skipping package step..."
          fi
