name: 'Pull request build'

run-name: 'Pull request build [PR#${{ github.ref_name }}] #${{ github.run_number }}'

on:
  pull_request:
    branches:
      - 'main'
      - 'release/**'

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout the branch
        uses: actions/checkout@v4
      - 
        name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - 
        name: Install Node modules
        run: npm install
      - 
        name: Test
        run: npm test
      - 
        name: Check dist
        run: |
          npx ncc build src/main/js/index.js -o tmp --minify
          actual_hash=$(sha256sum dist/index.js | awk '{print $1}')
          expected_hash=$(sha256sum tmp/index.js | awk '{print $1}')

          echo "Expected hash: $expected_hash"
          echo "Actual hash:   $actual_hash"

          if [ "$expected_hash" != "$actual_hash" ]; then
            echo "❌ The dist/index.js file is out of sync with the source."
            echo "💡 Please run \`npm run package\` and commit the result."
            exit 1
          else
            echo "✅ dist/index.js is up to date."
          fi
    
