name: 'Pull request build'

run-name: 'Pull request build [PR#${{ github.ref_name }}] #${{ github.run_number }}'

on:
  pull_request:
    branches:
      - 'main'
      - 'release/**'

jobs:
  review:
    permissions:
      contents: 'read'
      pull-requests:  'write'

    uses: newsome-solutions-ltd/developer-services-workflows/.github/workflows/pull_request_ai_review.yaml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      repository: ${{ github.repository }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}

  build:
    permissions:
      contents: 'write'
    
    uses: newsome-solutions-ltd/developer-services-workflows/.github/workflows/github_action_node_build.yaml@feature/39-node20-action-workflows
    if: github.event_name == 'pull_request'
    with:
      github_branch: ${{ github.head_ref }}
    